version: '3.7'

services:
  nginx-exporter:
    image: quay.io/martinhelmich/prometheus-nginxlog-exporter:v1
    container_name: nginx-exporter
    command: /mnt/nginxlogs/export.log -config-file /etc/exporter.hcl
    networks:
      - backend
    ports:
      - 4040:4040
    volumes:
      - nginx-logs:/mnt/nginxlogs
      - ./nginx/exporter.hcl:/etc/exported.hcl
    
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    networks:
      - backend
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - nginx-logs:/var/log/nginx

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - backend
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    env_file:
      - ./grafana/config.monitoring
    depends_on:
      - prometheus
    networks:
      - backend
    ports:
      - 3000:3000
    volumes:
      - grafana-provisioning:/etc/grafana/provisioning
      - grafana-data:/var/lib/grafana

  web-app:
    image: python:latest
    command: python -m http.server 8080
    restart: unless-stopped
    networks:
      - backend

networks:
  backend:

volumes:
  nginx-logs:
  prometheus-data:
  grafana-data:
  grafana-provisioning: